name: Docker Android CI

on:
  push:
    branches: ['feature/*']

jobs:

  # Builds a test image.
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build minimal Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: c0rrre/docker-android:test
          build-args: INSTALL_ANDROID_SDK=0
